### PR TITLE
fix: typo in subscribe URL blocking subscriptions

### PR DESCRIPTION
**Pull request by Vinnl**
This looked like a typo, and I _think_ is the cause of the subscribing not working for me at the moment. I also tried running the NPM task `docs`, but I saw it also included stuff like updating a version number to 0.2.0 even though this'd only be a patch release, so I left that be for now.

Do let me know if anything else is required.

### CODE REVIEW

**Comment by ariamckinley** [comment]
:+1: thanks for this

**Comment by Vinnl** [comment]
Thanks @garetmckinley. At the risk of sounding overly impatient - any chance of there coming a new release with this patch included? It's kinda breaking the subscribe form on my site, and even though it's not seeing many visitors yet, it's making me a bit uneasy :P

**Comment by ariamckinley** [comment]
No worries, you're not being overly impatient, I'm just glad somebody has found this library useful :blush: 

I pushed a new version `0.2.1`, let me know if this resolves your issues!

**Comment by Vinnl** [comment]
Hmm, it's still not working entirely as I hoped, but at least it solves this particular bug - thanks!

**Comment by ariamckinley** [comment]
Anything I can do to help?

**Comment by Vinnl** [comment]
Not sure yet, it might just be my local setup, or because I'm using multiple instances of the form on a single page - I've yet to dive into it. If you visit https://flockademic.com/ and enter your email address, pressing the submit button ("Join") doesn't do anything for me. Pressing "Enter" to submit does work, but then Tinyletter doesn't recognise my email address ("That email doesn't look right. Please try again."), which might have to do with my having to enter a Captcha first.

If you'd care to take a quick look at [the source code](https://gitlab.com/Flockademic/Flockademic/blob/master/stacks/frontend/src/components/tinyletterTeaser/component.tsx) to check if you see anything unexpected. that'd be much appreciated, but definitely don't feel pressured to spend any time at all on this :)

**Comment by ariamckinley** [comment]
I think the issue might be the submit button, try using an `input[type="submit"]`, like `<input type="submit" value="Subscribe"/>`

**Comment by Vinnl** [comment]
Huh odd, I wonder why I made that a `type="button"`. That [does indeed solve](http://62-clicking-the-submit-button-does-not-work-in-tinyletter-email.flockademic.com/) the clicking issue, thanks! Any chance you also have immediate insight into why TL doesn't recognise email addresses? :)

**Comment by Vinnl** [comment]
Found it - apparently the `input` element needs to have a `name="email"` attribute as well. I can't imagine my never having tested this, but I also can't imagine this ever having worked... :P Ah well.

**Comment by Vinnl** [comment]
Oh, and I just noticed that react-tinyletter is supposed to set that attribute itself. The reason it was failing was that the `email` field was not a direct descendant of `<TinyLetter>`, but wrapped in a `<div>`. Thus, when react-tinyletter iterates over its children to check for the `type="email"`, it only finds that `<div>`.

I've now updated the code to make the email field a direct descendant, and style the components using a different selector.

**Pull request merged**
